---
site_name: Kevel
site_description: Kubectl client with frictionless version switching.
site_url: https://kevel.readthedocs.io/

repo_name: germainlefebvre4/kevel
repo_url: https://github.com/germainlefebvre4/kevel

theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.code.copy

plugins:
  - search:
      lang: en
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_if_no_docstring: false
            show_docstring_description: true
            show_docstring_parameters: true
            show_docstring_examples: true
            docstring_section_style: table

nav:
  - Kevel: index.md
  - "Getting started": getting-started.md
  - Contributing: contributing.md
  - FAQ: faq.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - tables
  - footnotes
  - extra
  - mkdocs-click
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  # - mdx_include:
  #     base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details

watch:
  - docs/

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/germainlefebvre4/kevel
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/germainlefebvre4/kevel

copyright: Copyright &copy; 2024 Germain Lefebvre
